name: ci

on:
  - "push"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # This is the a separate action that sets up buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: set branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#ref/heads/})" >> $GITHUB_ENV
      - name: set branch name2
        shell: bash
        run: echo "NAMED_BRANCH=${BRANCH_NAME}-${GTIHUB-SHA:0:10}" >> $GITHUB_ENV
      # And make it available for the builds
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kmurakami/nextjs-test2:${{ env.NAMED_BRANCH }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: runner
