name: ci2

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: echo {{ github.event_name }}
